Mroonga 10.11への対応を追加する
cre-ne-jp/log-archiver pull request #254
Opened 2021-02-22 03:31 UTC by ochaochaocha3

Mroonga 10.11を使った場合でもデータベースのマイグレーションが最後まで進むように直しました。

Mroonga 10.11ではインプレースの `ALTER TABLE` の挙動が変わってエラーが発生するようになっていました。このエラーは `channel_last_speeches` -> `conversation_messages` の外部キー制約があると発生しました。そこで、`ALTER TABLE conversation_messages` の前にこの外部キー制約を削除するようにして、エラーを防ぎました。

2021-02-22 16:11 UTC, koi-chan requested changes

2021-02-22 16:11 UTC, koi-chan commented on db/migrate/20170617130524_recreate_conversation_messages_irc_user_id.rb
> +    remove_foreign_key :channel_last_speeches, :conversation_messages
まっさらな(db:create直後の)テーブルに対してマイグレーションを実施したところ、次のエラーを出して異常停止しました。

```
[外部キー制約の削除: channel_last_speeches -> conversation_messages]
-- remove_foreign_key(:channel_last_speeches, :conversation_messages)
rails aborted!
StandardError: An error has occurred, all later migrations canceled:

Table 'channel_last_speeches' has no foreign key for conversation_messages
/home/server-admin/git/hub/log-archiver/vendor/bundle/ruby/2.6.0/gems/activerecord-6.1.1/lib/active_record/connection_adapters/abstract/schema_statements.rb:1504:in `foreign_key_for!'
```

MySQL 8.0.23 + Mroonga 10.11 @ CentOS8 です。

2021-02-23 09:20 UTC, ochaochaocha3 commented
外部キー制約があるか調べる処理を追加してみましたが、MySQL 8.0だとうまく検出できないみたいですね。もう少し調べてみます。

2021-02-23 10:12 UTC, ochaochaocha3 commented
どうもMySQL 8.0の場合は `SHOW CREATE TABLE` では外部キー制約が設定されておらず、一方でGroonga側では設定されているという矛盾した状態になるようです。どちらかというとMySQL側の問題のように見えます。

2021-02-23 15:11 UTC, ochaochaocha3 commented
だんだん原因が分かってきました。MySQL 8.0でも外部キー制約は設定されているのですが、`FOREIGN KEY` として表示されないという状態のようです。

以下、20170408163604の時点での実行結果です。

MySQL 5.7.33 + Mroonga 11.00で `SHOW CREATE TABLE channel_last_speeches` を実行した結果：

```sql
CREATE TABLE `channel_last_speeches` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `channel_id` int(11) DEFAULT NULL,
  `conversation_message_id` int(11) DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  KEY `index_channel_last_speeches_on_channel_id` (`channel_id`),
  KEY `index_channel_last_speeches_on_conversation_message_id` (`conversation_message_id`),
  CONSTRAINT `channel_id` FOREIGN KEY (`channel_id`) REFERENCES `log_archiver_test`.`channels` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `conversation_message_id` FOREIGN KEY (`conversation_message_id`) REFERENCES `log_archiver_test`.`conversation_messages` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=Mroonga DEFAULT CHARSET=utf8mb4
```

MySQL 8.0.23 + Mroonga 11.00で `SHOW CREATE TABLE channel_last_speeches` を実行した結果：

```sql
CREATE TABLE `channel_last_speeches` (
  `id` int NOT NULL AUTO_INCREMENT,
  `channel_id` int DEFAULT NULL,
  `conversation_message_id` int DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  KEY `index_channel_last_speeches_on_channel_id` (`channel_id`),
  KEY `index_channel_last_speeches_on_conversation_message_id` (`conversation_message_id`)
) ENGINE=Mroonga DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci
```

MySQL 8.0でも、`ENGINE=InnoDB` の場合は `CONSTRAINT FOREIGN KEY` が表示されるので、これはMroongaの問題だと思います。当面の間は、MySQL 8.0 + Mroongaはこの矛盾があるため正常に使えないといえそうです（そのため、MySQL 5.7限定で通ると見なしてもいいでしょうか？）。Mroonga側にもissueを立ててみます。

2021-02-23 16:27 UTC, ochaochaocha3 commented
Mroongaのリポジトリにissueを立てました: mroonga/mroonga#393

2021-02-25 18:20 UTC, koi-chan commented
Mroonga 側のバグにより MySQL 8.0 との連携が上手くいかないのが原因なのですね。
でしたらこのPRはマージし、Mroonga 側の修正を待とうと思います。実装だけでなく調査までやっていただきありがとうございます。

2021-02-25 18:20 UTC, koi-chan approved these changes

2021-02-25 18:21 UTC, merged